default: &default
  adapter: postgresql
  database: <%= ENV["DATABASE_URL"] %>
  encoding: utf8
  min_messages: warning
  # 1(web_concurrency) * 5(threads) + 13(sidekiq concurrency) + 1(rails console) <= 20 (pg connections limit)
  pool: <%= ENV["MAX_THREADS"] || 5 %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

development:
  <<: *default
  database: <%= "#{ENV['DATABASE']}_dev" %>

test:
  <<: *default
  database: <%= "#{ENV['DATABASE']}_test" %>

production:
  <<: *default
